### ISSUE TITLE
This plugin breaks Jupyter Lab styles

### ISSUE THREAD

**Issue by MordorianGuy** [ploomber/jupysql-plugin#109] opened 2024-03-19 12:25 UTC
The plugin (I tested only it without jupysql with Jupyter Lab 4.1.5) breaks the dark theme and biases the placement of icons and visual elements.
![изображение](https://github.com/ploomber/jupysql-plugin/assets/100205963/da8b00d9-906c-46ab-8c87-5c1a6c708b6c)

**Comment by edublancas** [comment] 2024-03-19 15:53
thanks for the feedback. I think this is related to https://github.com/ploomber/jupysql-plugin/issues/101

**Comment by krassowski** [comment] 2024-07-19 08:40
FYI this was also recently reported in https://discourse.jupyter.org/t/annoying-white-background-on-tabs/27027

**Comment by psychemedia** [comment] 2024-08-28 14:43
I've just come across this in the way that tooltips/completion pop-ups get broken by the bootstrap theming.

![image](https://github.com/user-attachments/assets/fa599a5a-3d00-4f5d-96f2-28711a32c0fb)

**Comment by edublancas** [comment] 2024-08-30 18:42
I believe this is a duplicate of: https://github.com/ploomber/jupysql-plugin/issues/101

I assigned this to someone on my team, sorry for the trouble!

**Comment by edublancas** [comment] 2024-09-05 05:23
fixed by https://github.com/ploomber/jupysql-plugin/pull/118

credits to @rschroll, thanks for your contribution!

**Closed** 2024-09-05 05:24 UTC
